### ISSUE TITLE
License on semaphores

### ISSUE THREAD

**Issue by mudlord** [libretro/libretro-common#117]
I noticed the semaphore implementation using rthreads is under a GPL license.

Is there any alternatives to GPL?

**Comment by bparker06** [comment]
Actually GPL code is not allowed in libretro-common as it could make the API and other projects that use it GPL by extension. This needs to be removed... thankfully these functions are not actually being used.

**Comment by rybot666** [comment]
You know, libretro is a great project and the fact it's OSS is wonderful, but really guys. Banning people from it for _talking_ about licensing? Come on...

**Comment by twinaphex** [comment]
The person was not banned at all, I would not jump to premature conclusions about situations you are not involved in.
