### ISSUE TITLE
(cdrom.c) warning: implicit declaration of function ‘strcasestr’

### ISSUE THREAD

**Issue by negativeExponent** [libretro/libretro-common#143]
```
CXX libretro.cpp
libretro-common/cdrom/cdrom.c: In function ‘cdrom_get_available_drives’:
libretro-common/cdrom/cdrom.c:1394:20: warning: implicit declaration of function ‘strcasestr’; did you mean ‘strcasecmp’? [-Wimplicit-function-declaration]
 1394 |                if (strcasestr(mods->elems[i].data, "sg "))
      |                    ^~~~~~~~~~
      |                    strcasecmp
CC libretro-common/cdrom/cdrom.c
```
**#define _GNU_SOURCE** should be defined before #include <string.h> when using strcasestr() since its a nonstandard extension. But since this is in the libretro-common and i'm unfamiliar with other systems that would use this, ill leave it to someone who knows better to silence some of the warnings.

**Comment by jdgleaver** [comment]
It looks like we were just missing a compatibility header. I added it here: https://github.com/libretro/RetroArch/pull/11414

(I'm sure twinaphex will resync the repos once it gets merged)
