### ISSUE TITLE
arm thumb2 support

### ISSUE THREAD

**Issue by repojohnray** [libretro/libretro-common#20]
Here is below a patch to add ARM thumb2 support. Tested using gcc-5.4 (-with-arch=armv7-a --with-tune=cortex-a7 --with-fpu=neon-vfpv4 --with-float=hard --with-mode=thumb) and libretro-dosbox.

--- armeabi.c.orig      2016-07-25 22:40:54.000000000 +0200
+++ armeabi.c   2016-07-25 22:42:58.000000000 +0200
@@ -22,7 +22,25 @@
 static thread_local uint32_t co_active_buffer[64];
 static thread_local cothread_t co_active_handle;
 
-asm (
+#if defined(__thumb2__)
+  asm (
+      ".thumb\n"
+      ".align 2\n"
+      ".globl co_switch_arm\n"
+      ".globl _co_switch_arm\n"
+      "co_switch_arm:\n"
+      "_co_switch_arm:\n"
+      "  mov r3, sp\n"
+      "  stmia r1!, {r4, r5, r6, r7, r8, r9, r10, r11}\n"
+      "  stmia r1!, {r3, lr}\n"
+      "  ldmia r0!, {r4, r5, r6, r7, r8, r9, r10, r11}\n"
+      "  ldmfd r0!, { r3 }\n"
+      "  mov sp, r3\n"
+      "  ldmfd r0!, { r3 }\n"
+      "  mov pc, r3\n"
+       );
+#else /*defined(__thumb2__)*/
+  asm (
       ".arm\n"
       ".align 4\n"
       ".globl co_switch_arm\n"
@@ -32,6 +50,7 @@
       "  stmia r1!, {r4, r5, r6, r7, r8, r9, r10, r11, sp, lr}\n"
       "  ldmia r0!, {r4, r5, r6, r7, r8, r9, r10, r11, sp, pc}\n"
     );
+#endif /*defined(__thumb2__)*/
 
 /* ASM */
 void co_switch_arm(cothread_t handle, cothread_t current);

**Comment by repojohnray** [comment]
thumb2 is with double underline before and after.

**Comment by repojohnray** [comment]
.

**Comment by twinaphex** [comment]
Added this, thanks
