### ISSUE TITLE
RETRO_DEVICE_LIGHTGUN API was not suitable for Saturn/PlayStation

### ISSUE THREAD

**Issue by hiddenasbestos** [libretro/libretro-common#51]
Hi, sorry if this comes across badly but I wanted to share my negative experience of using the RETRO_DEVICE_LIGHTGUN API while adding lightgun support to the Saturn and PlayStation cores - my hope is we can improve it. I was unable to use it to support the guns on these cores and had to misuse other APIs to get the result I wanted.

My main problems were:

1. The RETRO_DEVICE_ID_LIGHTGUN_X/Y position values are relative, like a mouse - this seems at odds with how CRT lightgun technology works (and therefore naturally not suited as inputs to systems designed when CRTs were in use). The cores I was working with were expecting an absolute screen position as input - presumably something out there uses deltas?

Fortunately I was able to use the RETRO_DEVICE_ID_POINTER_X/Y instead - but this isn't what it was designed for and presumably a front-end could elect not to provide input on that channel? I'd suggest we add RETRO_DEVICE_ID_LIGHTGUN_SCREEN_X/Y and implement it in the same way as the pointer API.

---

2. The API is missing 'id values' for generic auxiliary controls e.g. Guncon has A, B action buttons, Justifier has a single Aux button, GunCon2 also has a d-pad. These will also need to be remappable.

This should be easy to fix -- just adding a few more constants, eg.

#define RETRO_DEVICE_ID_LIGHTGUN_DPAD_UP
#define RETRO_DEVICE_ID_LIGHTGUN_DPAD_DOWN 
#define RETRO_DEVICE_ID_LIGHTGUN_DPAD_LEFT
#define RETRO_DEVICE_ID_LIGHTGUN_DPAD_RIGHT

#define RETRO_DEVICE_ID_LIGHTGUN_AUX1
#define RETRO_DEVICE_ID_LIGHTGUN_AUX2
#define RETRO_DEVICE_ID_LIGHTGUN_AUX3
#define RETRO_DEVICE_ID_LIGHTGUN_AUX4

---

3. In RetroArch there's no way to remap the mouse buttons used to generate the action inputs (trigger, start, pause, ...), or to assign joypad or keyboard controls to these actions. In the PSX/Saturn cores I had to use the mouse API to read buttons directly and provide suitable mappings and options at the core level. Again, misusing an API as a work-around and doing work the front-end should be responsible for.

---

Hope I've not come across negative with this - but imho the lightgun API needs work. I'm hoping it's not too late to do something about this and get the ball rolling to improve it for all cores - I don't think it's far off. I'd be interested to know if other cores are also using work-arounds? and what their experiences were in doing so. It would be a shame to hold off from 'breaking' an API that no-one is actually using.

**Comment by fr500** [comment]
I don't think it has been used anywhere at all, and since you've been doing the work I think you should go ahead and come up with an implementation.

From the frontend side of things I guess the lightgun is just a pointer device?

I just checked libretro.h and it seems it was modeled after zapper / super scope

**Comment by fr500** [comment]
I guess mouse button remapping was never considered, since there were just 2, now that there are just 5 we could set descriptors for them on the core to provide nice names for remapping.

Remapping is a frontend feature though, I can try to hook that up once I move gamepad remapping to keymapper.c

**Comment by hiddenasbestos** [comment]
Okay great, I'm happy to carry on and put something together as a proposal for libretro.h, from the perspective of a core.

One other goal I have is a front-end thing and that is to add a driver for the DolphinBar in it's special 'mode 4'. In this mode it lets you sync up to 4 wiimotes and sends out data over USB as proper input devices, not just mouse emulation. This would let you have multi-player games.  I'll need to take a look at the Dolphin source code to see how to access it.

**Comment by hiddenasbestos** [comment]
I've done a bunch of research into the buttons found on light-guns from the 3rd-6th generation of consoles. The Guncon 2 (for the PlayStation 2) is the peak of lightgun technology before it diverges heavily after the advent of motion controls.

My proposed change to libretro.h are found below.

It breaks the API in the following ways:
 * Deprecating the relative mode X/Y
 * Unifying Start and Pause macros

Other than that I think I've done a good job in extending the API to add the new functionality we'd need for 5th Gen consoles and beyond. Also preserving the legacy SuperScope macros for cursor and turbo buttons.

This will definitely need remapping support in the front-end as there's just a huge amount of variety in what features are supported on each console's gun and if you're limited to emulating via a mouse you'll likely have far fewer buttons available than on a G-Con 2. You will very likely need to map keyboard or controller buttons to secondary actions (such as pause or d-pad, etc.) or make use of the new mouse 4/5 buttons.

```
/* The LIGHTGUN device is similar to Guncon-2 for PlayStation 2.
 * It reports X/Y coordinates in screen space (similar to the pointer)
 * as well as reporting on/off screen state. It features a trigger, 
 * start/select buttons, four auxiliary action buttons and a 
 * directional pad.
 */
#define RETRO_DEVICE_LIGHTGUN     4

/* Id values for LIGHTGUN types. */
#define RETRO_DEVICE_ID_LIGHTGUN_SCREEN_X     13 /*Absolute*/
#define RETRO_DEVICE_ID_LIGHTGUN_SCREEN_Y     14 /*Absolute*/
#define RETRO_DEVICE_ID_LIGHTGUN_IS_OFFSCREEN 15
#define RETRO_DEVICE_ID_LIGHTGUN_TRIGGER       2
#define RETRO_DEVICE_ID_LIGHTGUN_AUX_A         3
#define RETRO_DEVICE_ID_LIGHTGUN_AUX_B         4
#define RETRO_DEVICE_ID_LIGHTGUN_START         5
#define RETRO_DEVICE_ID_LIGHTGUN_SELECT        6
#define RETRO_DEVICE_ID_LIGHTGUN_AUX_C         7
#define RETRO_DEVICE_ID_LIGHTGUN_AUX_D         8
#define RETRO_DEVICE_ID_LIGHTGUN_DPAD_UP       9
#define RETRO_DEVICE_ID_LIGHTGUN_DPAD_DOWN    10
#define RETRO_DEVICE_ID_LIGHTGUN_DPAD_LEFT    11
#define RETRO_DEVICE_ID_LIGHTGUN_DPAD_RIGHT   12
/* DEPRECATED LIGHTGUN */
#define RETRO_DEVICE_ID_LIGHTGUN_X             0 /*Relative*/
#define RETRO_DEVICE_ID_LIGHTGUN_Y             1 /*Relative*/
#define RETRO_DEVICE_ID_LIGHTGUN_CURSOR        3 /*= Aux:A*/
#define RETRO_DEVICE_ID_LIGHTGUN_TURBO         4 /*= Aux:B*/
#define RETRO_DEVICE_ID_LIGHTGUN_PAUSE         5 /*Remapped to Start*/
```

**Comment by hiddenasbestos** [comment]
Im thinking a dedicated off-screen shot input might be useful too. It'd add the ability to have "auto-reload" which was a feature of many 3rd party guns. However it could also be simulated in the front end (assuming an " is-on-screen " check is done after every shot) which would keep the core a bit cleaner.

**Comment by hiddenasbestos** [comment]
I revised the new API. Removed AUX_D since this has no meaning for a Guncon 2 or any other gun preceding it (if in future there is need for extra buttons those can be added then).

Also added a forced off-screen shot request. A front-end can request that of a core to perform an auto-reload - or replicate the right-click to reload of Virtua Cop 2 on PC.

```
/* Id values for LIGHTGUN aiming. */
#define RETRO_DEVICE_ID_LIGHTGUN_SCREEN_X        12 /*Absolute Position*/
#define RETRO_DEVICE_ID_LIGHTGUN_SCREEN_Y        13 /*Absolute*/
#define RETRO_DEVICE_ID_LIGHTGUN_IS_OFFSCREEN    14 /*Status Check*/
/* buttons */
#define RETRO_DEVICE_ID_LIGHTGUN_TRIGGER          2
#define RETRO_DEVICE_ID_LIGHTGUN_OFFSCREEN_SHOT  15 /*forced*/
#define RETRO_DEVICE_ID_LIGHTGUN_AUX_A            3
#define RETRO_DEVICE_ID_LIGHTGUN_AUX_B            4
#define RETRO_DEVICE_ID_LIGHTGUN_START            5
#define RETRO_DEVICE_ID_LIGHTGUN_SELECT           6
#define RETRO_DEVICE_ID_LIGHTGUN_AUX_C            7
#define RETRO_DEVICE_ID_LIGHTGUN_DPAD_UP          8
#define RETRO_DEVICE_ID_LIGHTGUN_DPAD_DOWN        9
#define RETRO_DEVICE_ID_LIGHTGUN_DPAD_LEFT       10
#define RETRO_DEVICE_ID_LIGHTGUN_DPAD_RIGHT      11
/* deprecated */
#define RETRO_DEVICE_ID_LIGHTGUN_X                0 /*Relative*/
#define RETRO_DEVICE_ID_LIGHTGUN_Y                1 /*Relative*/
#define RETRO_DEVICE_ID_LIGHTGUN_CURSOR           3 /*= Aux:A*/
#define RETRO_DEVICE_ID_LIGHTGUN_TURBO            4 /*= Aux:B*/
#define RETRO_DEVICE_ID_LIGHTGUN_PAUSE            5 /*Remapped to Start*/
```

**Comment by hiddenasbestos** [comment]
I've made some good initial progress. The new API has let me strip out a bunch of code from the core and move it to the front-end where it belongs. From a core point of view the code is much cleaner now and I've been able to use 100% light-gun calls to get the input I need. AFAICT the core side is now done.

The second part is to work on a patch for RetroArch to support this work from the front-end side. So far I've disabled any lightgun support on the platforms that have it and am now focusing on bringing the directinput driver back online with the new API - aiming is already working again (since it's just a tweaked copy of the pointer code), but the buttons are either hard coded or disabled.

The next step, to complete the first driver 100%, is to add user configurable bindings for all the new gun buttons. This will require being able to map keys, pad buttons and now mouse buttons to a list of 11 virtual gun buttons - same as when you bind inputs to the RetroPad.

Any tips @fr500 ? How does it fit in with other RetroArch plans? should I hold off? should I plow on?

Probably I'd proceed something like this:

* Add new bindings to the list.
* Get them displaying on the "User 1 Binds" sub-menu.
* Make sure it's saving/loading to the config file properly.
* Get keyboard and joystick mappings working in the dinput driver.
* Add in mouse button support.

**Comment by hiddenasbestos** [comment]
There's a couple of things I wanted to ask about @twinaphex, in terms of avoiding 'breaking ABI'.

* If a new core requiring this new API (for the extra buttons) is used on an old front-end that only implements the old API then lightguns won't work. Is there anything I can do about this without building a whole suite of input remapping functionality into the core?

---

Also I'd like to unify the old START and PAUSE controls. I've not encountered any real-world device that has these as separate inputs (happy to be corrected). 

I originally decided to do that by changing the value of RETRO_DEVICE_ID_LIGHTGUN_PAUSE, however on reflection that would be bad, e.g. for old core binaries using new front-ends, so I changed it back. The new front-end can just route this to the new unified start/pause input internally to maintain compatibility - assuming of course that the core doesn't think start and pause should be different.

So the new libretro.h section is now:


```
/* Id values for LIGHTGUN aiming. */
#define RETRO_DEVICE_ID_LIGHTGUN_SCREEN_X        13 /*Absolute Position*/
#define RETRO_DEVICE_ID_LIGHTGUN_SCREEN_Y        14 /*Absolute*/
#define RETRO_DEVICE_ID_LIGHTGUN_IS_OFFSCREEN    15 /*Status Check*/
/* buttons */
#define RETRO_DEVICE_ID_LIGHTGUN_TRIGGER          2
#define RETRO_DEVICE_ID_LIGHTGUN_OFFSCREEN_SHOT  16 /*forced*/
#define RETRO_DEVICE_ID_LIGHTGUN_AUX_A            3
#define RETRO_DEVICE_ID_LIGHTGUN_AUX_B            4
#define RETRO_DEVICE_ID_LIGHTGUN_START            5
#define RETRO_DEVICE_ID_LIGHTGUN_SELECT           7
#define RETRO_DEVICE_ID_LIGHTGUN_AUX_C            8
#define RETRO_DEVICE_ID_LIGHTGUN_DPAD_UP          9
#define RETRO_DEVICE_ID_LIGHTGUN_DPAD_DOWN       10
#define RETRO_DEVICE_ID_LIGHTGUN_DPAD_LEFT       11
#define RETRO_DEVICE_ID_LIGHTGUN_DPAD_RIGHT      12
/* deprecated */
#define RETRO_DEVICE_ID_LIGHTGUN_X                0 /*Relative Position*/
#define RETRO_DEVICE_ID_LIGHTGUN_Y                1 /*Relative*/
#define RETRO_DEVICE_ID_LIGHTGUN_CURSOR           3 /*Use Aux:A*/
#define RETRO_DEVICE_ID_LIGHTGUN_TURBO            4 /*Use Aux:B*/
#define RETRO_DEVICE_ID_LIGHTGUN_PAUSE            6 /*Use Start*/

```

**Comment by hiddenasbestos** [comment]
I've implemented the binding in RetroArch on my local build and now have ability to bind keyboard/controller inputs to these new controls.

I decided to rename the rather cumbersome "off-screen shot" to just "reload".

Next to do is make the remapping feature work, so you can setup one gun config for your device and then remap it to the game/core. I got the descriptors coming through but the choices on the menu selections were from the retropad so I'll need to dig into the menu system a bit to figure it out.

The main things left are now:
* Ability to bind mouse buttons to controls so you can shoot with the mouse (I have this hard coded atm)
* Remapping, as mentioned above
* Updating the other input drivers to support the new API, based on the dinput implementation.
* Wait for patch https://github.com/libretro/RetroArch/pull/5762 to be applied, as the extra lightgun inputs break the 64 bind limit.

**Comment by hiddenasbestos** [comment]
This has been merged now, best to raise new issues for and discovered/remaining problems.
