### ISSUE TITLE
(Request) mGBA Sound Channel Switches

### ISSUE THREAD

**Issue by Big-the-Fat** [libretro/libretro-common#60]
It would be nice to have a core option to allow switching on and off audio channels in mGBA.  This feature exists in the standalone Windows build.

**Comment by mudlord** [comment]
Thats outside the scope of this repo.

Thats an emulator implementation issue, not the libretro-common repo.

**Comment by hizzlekizzle** [comment]
This issue can be opened at the libretro/mgba fork repo. There's nothing wrong with it, just that it's in the wrong place :)
