### ISSUE TITLE
[RPNG] Error in line 237

### ISSUE THREAD

**Issue by hizzlekizzle** [libretro/libretro-common#94]
When trying to use the --max-frames-ss option in RetroArch, the screenshot never gets taken because of a reported error in RPNG:

```
[INFO] Taking a screenshot before exiting...
[RPNG]: Error in line 237.
[ERROR] Could not take a screenshot before exiting.
```

That line [doesn't look particularly exciting](https://github.com/libretro/libretro-common/blob/499ce1874843a13d588973f54c99efadc3dfd229/formats/png/rpng.c#L237).

Happens in the latest nightly as of the time of this writing (11/7/2018)

**Comment by mudlord** [comment]
Tried a GDB trace? Thats all I can think of, having not dealt with GDB much at all.

**Comment by hizzlekizzle** [comment]
no, i'll try that this evening

**Comment by orbea** [comment]
@hizzlekizzle Maybe its counting lines without comments and/or spaces?

**Comment by hizzlekizzle** [comment]
@orbea ah, yeah, looks that way. It seems 237 is the GOTO_END_ERROR() from here:

```
211 | static bool rpng_save_image(const char *path,
212 | const uint8_t *data,
213 | unsigned width, unsigned height, unsigned pitch, unsigned bpp)
214 | {
215 | unsigned h;
216 | bool ret = true;
217 | struct png_ihdr ihdr = {0};
218 |  
219 | const struct trans_stream_backend *stream_backend = NULL;
220 | size_t encode_buf_size  = 0;
221 | uint8_t *encode_buf     = NULL;
222 | uint8_t *deflate_buf    = NULL;
223 | uint8_t *rgba_line      = NULL;
224 | uint8_t *up_filtered    = NULL;
225 | uint8_t *sub_filtered   = NULL;
226 | uint8_t *avg_filtered   = NULL;
227 | uint8_t *paeth_filtered = NULL;
228 | uint8_t *prev_encoded   = NULL;
229 | uint8_t *encode_target  = NULL;
230 | void *stream            = NULL;
231 | uint32_t total_in       = 0;
232 | uint32_t total_out      = 0;
233 | RFILE *file             = filestream_open(path,
234 | RETRO_VFS_FILE_ACCESS_WRITE,
235 | RETRO_VFS_FILE_ACCESS_HINT_NONE);
236 | if (!file)
237 | GOTO_END_ERROR();
```

**Comment by hizzlekizzle** [comment]
Hmm. I still get it using today's build from the buildbot in Windows using this CLI invocation:
`.\retroarch.exe --verbose -L cores\snes9x_libretro.dll ..\roms\240pSuite.sfc --max-frames 500 --max-frames-ss --max-frames-ss-path .\`
If I use --max-frames=500, it treats it as a malformed command and spits out the --help text.

**Comment by hizzlekizzle** [comment]
Ah, yeah, the error comes from !file, so I guess it's needing a filename there. That seems to work alright in linux. I'll test in Windows tomorrow. In the meantime, I'll close this issue and reopen if necessary.

**Comment by orbea** [comment]
I made a PR to fix the file name issue discussed above. https://github.com/libretro/RetroArch/pull/8014

**Comment by CWSpear** [comment]
I saw this same error, but reproduced it in a different way (but I think it's related). I enabled RetroAchievements and the "Take a screenshot when you get an achievement" option. Any time I do an achievement, I get a message in RetroArch, "Failed to take screenshot." Regular screenshots work, just not the auto ones for achievements.

I'm on Mac with RetroArch v1.7.5. I got the same exact error as the title in the console when I got an achievement. I started RetroArch with this command (to get output to the console and see this error):

```
/Applications/RetroArch.app/Contents/MacOS/RetroArch --menu --verbose
```

Tested in a couple different NES games. I did get credit for the achievements, tho, just no screenshot proof 😢

**Comment by CWSpear** [comment]
Ok, I found the nightly builds. I tested `2019-01-27_RetroArch.dmg` from http://buildbot.libretro.com/nightly/apple/osx/x86_64/.

I still got this error when I got an achievement. Does that nightly include @orbea's PR? It should cuz it's merged, right?
