### ISSUE TITLE
[GLES2] Build failure in libretro-common

### ISSUE THREAD

**Issue by orbea** [libretro/libretro-common#98]
This issue is triggered by parallel-n64 with `FORCE_GLES=1` on Linux. Please see issue https://github.com/libretro/parallel-n64/issues/557.

However the point of failure is in libretro-common and I think this issue is also relevant here. Basically after mesa commit https://github.com/mesa3d/mesa/commit/f7d42ee7d319256608ad60778f6787c140badada it now contains the following typedef in `include/GLES2/gl2ext.h`.
```
typedef double GLdouble;
```

https://github.com/mesa3d/mesa/blob/3b2ad8b290215a4bd52be4e397c9ab5603b8b372/include/GLES2/gl2ext.h#L2947

While libretro-common contains the conflicting typedef in `include/glsm/glsm.h`.

https://github.com/libretro/libretro-common/blob/33c632195f54d2ce0be34c56f98bb1a2a4c98831/include/glsm/glsm.h#L35

And then includes `GLES2/gl2ext.h` in `include/glsym/rglgen_headers.h`.

https://github.com/libretro/libretro-common/blob/33c632195f54d2ce0be34c56f98bb1a2a4c98831/include/glsym/rglgen_headers.h#L56

This is not valid and will cause build issues.
```
In file included from ./libretro-common/include/glsm/glsmsym.h:26,
                 from mupen64plus-core/src/api/vidext_libretro.c:41:
./libretro-common/include/glsm/glsm.h:35:17: error: conflicting types for ‘GLdouble’
 typedef GLfloat GLdouble;
                 ^~~~~~~~
In file included from ./libretro-common/include/glsym/rglgen_headers.h:56,
                 from ./libretro-common/include/glsm/glsm.h:30,
                 from ./libretro-common/include/glsm/glsmsym.h:26,
                 from mupen64plus-core/src/api/vidext_libretro.c:41:
/usr/include/GLES2/gl2ext.h:2947:16: note: previous declaration of ‘GLdouble’ was here
 typedef double GLdouble;
                ^~~~~~~~
make: *** [Makefile:932: mupen64plus-core/src/api/vidext_libretro.o] Error 1
```
Removing the typedef from libretro-common will work, but I am not sure what if any issues that will cause with older mesa releases or other platforms.

Alternatively this patch can be used, but I am also not sure about the negative consequences.
```
diff --git a/libretro-common/include/glsym/rglgen_headers.h b/libretro-common/include/glsym/rglgen_headers.h
index 766efb63..3de538d6 100644
--- a/libretro-common/include/glsym/rglgen_headers.h
+++ b/libretro-common/include/glsym/rglgen_headers.h
@@ -53,6 +53,7 @@
 #include <GLES2/gl2ext.h>
 #elif defined(HAVE_OPENGLES2)
 #include <GLES2/gl2.h>
+#define GL_NV_path_rendering
 #include <GLES2/gl2ext.h>
 #elif defined(HAVE_OPENGLES1)
 #include <GLES/gl.h>
```
Or maybe the headers can be rearranged in a way to avoid this?

**Comment by orbea** [comment]
@twinaphex Any thoughts on how to best fix this?

**Comment by shantigilbert** [comment]
I am having this same issue as well, several cores fail to build, including parallel, mupen64 and Reicast

**Comment by orbea** [comment]
Unfortunately I haven't been able to get anyone to comment on how to fix this so its probably going to remain unfixed...

**Comment by shantigilbert** [comment]
@orbea That is a bummer, but at least your patch worked for me with all 3 cores I was having problems with, so thank you for that.
